apiVersion: v1
kind: Pod
metadata:
  name: ui-tests
  labels:
    app: ui-tests
spec:
  serviceAccountName: ui-tests
  securityContext:
    fsGroup: 1000
  containers:
  - name: ui-tests
    image: europe-west2-docker.pkg.dev/ssdc-rm-ci/docker/ssdc-rm-ui-tests:latest
    tty: true
    stdin: true
    imagePullPolicy: Always
    resources:
      requests:
        cpu: "1"
        memory: "1Gi"
      limits:
        cpu: "1"
        memory: "1Gi"
