platform: linux

image_resource:
  type: registry-image
  source:
    repository: gcr.io/google.com/cloudsdktool/cloud-sdk

params:
  SERVICE_ACCOUNT_JSON:
  GCP_PROJECT_NAME:
  KUBERNETES_CLUSTER:
  RESPONSE_OPERATIONS_URL:

inputs:
- name: ui-tests-repo

run:
  path: bash
  args:
    - -exc
    - |
      cat >~/gcloud-service-key.json <<EOL
      $SERVICE_ACCOUNT_JSON
      EOL

      # Use gcloud service account to configure kubectl
      gcloud auth activate-service-account --key-file ~/gcloud-service-key.json
      gcloud container clusters get-credentials ${KUBERNETES_CLUSTER} --zone europe-west2 --project ${GCP_PROJECT_NAME}



      apt update && apt install dnsutils -y
      IP_ADDRESS="$(dig -4 +short myip.opendns.com @resolver1.opendns.com)"
      echo $IP_ADDRESS





      kubectl delete pod ui-tests --wait || true

      kubectl apply -f ui-tests-repo/ui_tests_pod.yml

      kubectl wait --for=condition=Ready pod/ui-tests --timeout=200s

      # The sleep is to give kubectl time to attach properly, otherwise the first few log lines are lost
      kubectl exec -it ui-tests -- /bin/bash -c \
      "sleep 2; CYPRESS_BASE_URL=${RESPONSE_OPERATIONS_URL} npx cypress run"
